[package]
name = "ctrie-rs"
version = "0.1.0"
authors = ["David J. Lee <djl5@williams.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
